### ISSUE TITLE
More error

### ISSUE THREAD

**Issue by Owned67** [StefonMiller/CamBot#1]
`Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\discord\ext\commands\bot.py", line 632, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "F:\bot\CamBot-master\cogs\info_cog.py", line 5, in <module>
    import CamBot
  File "F:\bot\CamBot-master\CamBot.py", line 1172, in <module>
    client.run(keys[0])
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\bot\CamBot-master\CamBot.py", line 92, in <module>
    client.load_extension(f'cogs.{filename[:-3]}')
  File "C:\Python39\lib\site-packages\discord\ext\commands\bot.py", line 704, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Python39\lib\site-packages\discord\ext\commands\bot.py", line 635, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.info_cog' raised an error: IndexError: list index out of range
`

**Comment by StefonMiller** [comment]
Hello,

You need to create a "keys.txt" file in the data folder and put in your Twitter + Discord API keys. I did not include that file in the repository for obvious reasons.

**Comment by Owned67** [comment]
API key discord? token u mean? (ok added)

Successfully connected to SQLite database
Checking for site changes...
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<check() done, defined at F:\bot\CamBot-master\CamBot.py:113> exception=OperationalError('no such table: current')>
Traceback (most recent call last):
  File "F:\bot\CamBot-master\CamBot.py", line 137, in check
    item_status = check_for_updates("skins", check_item)
  File "F:\bot\CamBot-master\CamBot.py", line 414, in check_for_updates
    cursor.execute(sql, (update_category,))
sqlite3.OperationalError: no such table: current
Distributed scrap to 0 members
                We have logged in as BotTest#1234

**Comment by StefonMiller** [comment]
You need more keys in the keys.txt file. Along with the discord token, you need to get twitter and bitskins API keys. I have added a sample file to show you the format. As for your current error, you have no sqlite database. I have added a sample one you can use. Many of the tables have been emptied as they contain potentially sensitive data so you will have to populate them yourself.

**Comment by Owned67** [comment]
> You need more keys in the keys.txt file. Along with the discord token, you need to get twitter and bitskins API keys. I have added a sample file to show you the format. As for your current error, you have no sqlite database. I have added a sample one you can use. Many of the tables have been emptied as they contain potentially sensitive data so you will have to populate them yourself.

bitskin have removed rust so... ok thanks, populate sqlite? xD not for me...
